// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Pianivo - Mindful Scheduling",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Pianivo - Mindful Scheduling",
            targets: ["AppModule"],
            teamIdentifier: "D345267D4X",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .reminders(purposeString: "Receive appointment reminders with Pianivo"),
                .calendars(purposeString: "Pianivo needs calendar access to sync your appointments."),
                .contacts(purposeString: "Pianivo uses contacts to help you quickly fill in student details."),
                .faceID(purposeString: "Unlock Pianivo securely using Face ID."),
                .outgoingNetworkConnections()
            ],
            appCategory: .productivity
        )
    ],
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk", "12.17.0"..<"13.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseCore", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestore", package: "firebase-ios-sdk"),
                .product(name: "FirebaseStorage", package: "firebase-ios-sdk")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
