# Generated by Django 6.0 on 2025-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_status_business_email_business_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
