# Generated by Django 6.0 on 2026-01-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businessemployee_appointment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessemployee',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
