# Generated by Django 6.0 on 2026-01-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessemployee_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='employees_can_manage_appointments',
            field=models.BooleanField(default=True),
        ),
    ]
